export const GET_NOTES = 'GET_NOTES'
export const NEW_NOTE = 'NEW_NOTE'
export const SELECT_NOTE = 'SELECT_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const SAVE_NOTE = 'SAVE_NOTE'
export const RESAVE_NOTE = 'RESAVE_NOTE'
